<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.LoBMvTS' shared service.

return $this->privates['.service_locator.LoBMvTS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'logboek' => ['privates', '.errored..service_locator.LoBMvTS.App\\Entity\\Logboek', NULL, 'Cannot autowire service ".service_locator.LoBMvTS": it references class "App\\Entity\\Logboek" but no such service exists.'],
]);
