<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.JRHqsUH' shared service.

return $this->privates['.service_locator.JRHqsUH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'truck' => ['privates', '.errored..service_locator.JRHqsUH.App\\Entity\\Truck', NULL, 'Cannot autowire service ".service_locator.JRHqsUH": it references class "App\\Entity\\Truck" but no such service exists.'],
]);
