<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\TraceableValueResolver.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\LogboekController::delete' => ['privates', '.service_locator.LoBMvTS', 'get_ServiceLocator_LoBMvTSService.php', true],
    'App\\Controller\\LogboekController::edit' => ['privates', '.service_locator.LoBMvTS', 'get_ServiceLocator_LoBMvTSService.php', true],
    'App\\Controller\\LogboekController::index' => ['privates', '.service_locator.wEO.1mR', 'get_ServiceLocator_WEO_1mRService.php', true],
    'App\\Controller\\LogboekController::show' => ['privates', '.service_locator.LoBMvTS', 'get_ServiceLocator_LoBMvTSService.php', true],
    'App\\Controller\\TruckController::delete' => ['privates', '.service_locator.JRHqsUH', 'get_ServiceLocator_JRHqsUHService.php', true],
    'App\\Controller\\TruckController::edit' => ['privates', '.service_locator.JRHqsUH', 'get_ServiceLocator_JRHqsUHService.php', true],
    'App\\Controller\\TruckController::index' => ['privates', '.service_locator.UUqqAWA', 'get_ServiceLocator_UUqqAWAService.php', true],
    'App\\Controller\\TruckController::show' => ['privates', '.service_locator.JRHqsUH', 'get_ServiceLocator_JRHqsUHService.php', true],
    'App\\Controller\\UserController::delete' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController::edit' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController::show' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\LogboekController:delete' => ['privates', '.service_locator.LoBMvTS', 'get_ServiceLocator_LoBMvTSService.php', true],
    'App\\Controller\\LogboekController:edit' => ['privates', '.service_locator.LoBMvTS', 'get_ServiceLocator_LoBMvTSService.php', true],
    'App\\Controller\\LogboekController:index' => ['privates', '.service_locator.wEO.1mR', 'get_ServiceLocator_WEO_1mRService.php', true],
    'App\\Controller\\LogboekController:show' => ['privates', '.service_locator.LoBMvTS', 'get_ServiceLocator_LoBMvTSService.php', true],
    'App\\Controller\\TruckController:delete' => ['privates', '.service_locator.JRHqsUH', 'get_ServiceLocator_JRHqsUHService.php', true],
    'App\\Controller\\TruckController:edit' => ['privates', '.service_locator.JRHqsUH', 'get_ServiceLocator_JRHqsUHService.php', true],
    'App\\Controller\\TruckController:index' => ['privates', '.service_locator.UUqqAWA', 'get_ServiceLocator_UUqqAWAService.php', true],
    'App\\Controller\\TruckController:show' => ['privates', '.service_locator.JRHqsUH', 'get_ServiceLocator_JRHqsUHService.php', true],
    'App\\Controller\\UserController:delete' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController:edit' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController:show' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
