<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRQWRDHS\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRQWRDHS/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRQWRDHS.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRQWRDHS\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRQWRDHS\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RQWRDHS',
    'container.build_id' => '7e1d2b11',
    'container.build_time' => 1553296107,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRQWRDHS');
